In [6]:
import tensorflow as tf
tf.__version__

'2.4.0'

# Constant


In [7]:
# Defning a constant

tensor=tf.constant([[2,4], [5,6]])

In [8]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [11]:
# Getting value of constant

tensor.numpy()

array([[2, 4],
       [5, 6]], dtype=int32)

In [13]:
# We can also convert a numpy array back to the Tensorflow tensor as well
import numpy as np
np_tensor=np.array([[2,2,],[3,3]])

In [14]:
np_tensor

array([[2, 2],
       [3, 3]])

In [15]:
tensor_np=tf.constant(np_tensor)

In [16]:
tensor_np

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 2],
       [3, 3]])>

# Variable

In [17]:
# Defining a variable

tf_variable=tf.Variable([[1,2,3],[4,5,6]])

In [18]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [19]:
# Getting valu of a variable
tf_variable.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [22]:
# Changing specific value in variable
tf_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  4,   5,   6]], dtype=int32)>

In [23]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  4,   5,   6]], dtype=int32)>

# Operation between tensors

In [24]:
# Addition between a scalar and a tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [25]:
tensor+2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 8]], dtype=int32)>

In [26]:
# Multiplication between a scalar and tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [27]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [10, 12]], dtype=int32)>

# Using numpy functions on tensor


In [28]:
# Getting square of all numbers in tensorflow object
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [29]:
np.square(tensor)

array([[ 4, 16],
       [25, 36]], dtype=int32)

In [30]:
# Getting square root of all numbers 
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [31]:
np.sqrt(tensor)

array([[1.41421356, 2.        ],
       [2.23606798, 2.44948974]])

# Dot products between two tensors

In [32]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [36]:
tensor_1=tensor+1
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7]], dtype=int32)>

In [37]:
np.dot(tensor,tensor_1)

array([[30, 38],
       [51, 67]], dtype=int32)

# Strings in Tensorflow 2.0

In [38]:
tf_string=tf.constant("Tensorflow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

### Simple string operations

In [40]:
# length of string
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [41]:
# unicode decode string
tf.strings.unicode_decode(tf_string, "UTF-8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [42]:
tf_array=tf.constant(["machine learning", "deep learning","NLP"])

In [43]:
tf_array

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'machine learning', b'deep learning', b'NLP'], dtype=object)>

In [44]:
# Iterating through TF string array
for string in tf_array:
    print(string)

tf.Tensor(b'machine learning', shape=(), dtype=string)
tf.Tensor(b'deep learning', shape=(), dtype=string)
tf.Tensor(b'NLP', shape=(), dtype=string)
